import "./globals.css";
import { Patrick_Hand } from 'next/font/google';

const patrick_font = Patrick_Hand({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-patrick'
})


export const metadata = {
  title: "Habitly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${patrick_font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
