import "./globals.css";
import { Patrick_Hand } from 'next/font/google';
import { getUserInfo } from "@/components/auth/getUserInfo";
import { AuthProvider } from "@/components/auth/AuthProvider";
import Navbar from "@/components/layout/navbar";

const patrick_font = Patrick_Hand({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-patrick'
})


export const metadata = {
  title: "Habitly",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  const user = await getUserInfo();

  return (
    <html lang="en">
      <body
        className={`${patrick_font.variable} antialiased`}
      >
        <AuthProvider initialUser={user}>
          <Navbar/>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
